// <auto-generated />
using System;
using GabrielOS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GabrielOS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331020257_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("GabrielOS.Domain.Entities.CheckIn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Clarity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Energy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FreeText")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mood")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhysicalState")
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestedMode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tension")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TopConcern")
                        .HasColumnType("TEXT");

                    b.Property<string>("TopPriority")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("CheckIns");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.CycleFocus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Thesis")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CycleFocuses");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.CycleFocusGoal", b =>
                {
                    b.Property<Guid>("CycleFocusId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("TEXT");

                    b.HasKey("CycleFocusId", "GoalId");

                    b.HasIndex("GoalId");

                    b.ToTable("CycleFocusGoals");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.Decision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChosenOption")
                        .HasColumnType("TEXT");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GoalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutcomeNotes")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PillarId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProblemStatement")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rationale")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RisksAccepted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TradeOffs")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.HasIndex("PillarId");

                    b.HasIndex("UserId");

                    b.ToTable("Decisions");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("HorizonType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MainRisk")
                        .HasColumnType("TEXT");

                    b.Property<string>("NextAction")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PillarId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SuccessCriteria")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WhyItMatters")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PillarId");

                    b.HasIndex("UserId", "Status", "Priority");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.Initiative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NextAction")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("Initiatives");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DecisionId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Energy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GoalId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Intensity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Mood")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PillarId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DecisionId");

                    b.HasIndex("GoalId");

                    b.HasIndex("PillarId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.Metric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PillarId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PillarId");

                    b.HasIndex("UserId", "PillarId", "Date");

                    b.ToTable("Metrics");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.MonthlyReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AISummary")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Highlights")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyLearnings")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lowlights")
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NextMonthIntentions")
                        .HasColumnType("TEXT");

                    b.Property<string>("PillarScoresJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("MonthlyReviews");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.Pattern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Trigger")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Patterns");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.Pillar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentState")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Trend")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vision")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SortOrder");

                    b.ToTable("Pillars");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GoalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InitiativeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNextAction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Priority")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.HasIndex("InitiativeId");

                    b.HasIndex("UserId");

                    b.ToTable("TaskItems");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentPhase")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferencesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.WeeklyReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AISummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvoidedThings")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnergyDrains")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnergyGains")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frictions")
                        .HasColumnType("TEXT");

                    b.Property<string>("MainInsight")
                        .HasColumnType("TEXT");

                    b.Property<string>("NextWeekFocus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PillarScoresJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WeekStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("Wins")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "WeekStart")
                        .IsUnique();

                    b.ToTable("WeeklyReviews");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.CheckIn", b =>
                {
                    b.HasOne("GabrielOS.Domain.Entities.User", "User")
                        .WithMany("CheckIns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.CycleFocus", b =>
                {
                    b.HasOne("GabrielOS.Domain.Entities.User", "User")
                        .WithMany("CycleFocuses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.CycleFocusGoal", b =>
                {
                    b.HasOne("GabrielOS.Domain.Entities.CycleFocus", "CycleFocus")
                        .WithMany("CycleFocusGoals")
                        .HasForeignKey("CycleFocusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GabrielOS.Domain.Entities.Goal", "Goal")
                        .WithMany("CycleFocusGoals")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CycleFocus");

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.Decision", b =>
                {
                    b.HasOne("GabrielOS.Domain.Entities.Goal", "Goal")
                        .WithMany()
                        .HasForeignKey("GoalId");

                    b.HasOne("GabrielOS.Domain.Entities.Pillar", "Pillar")
                        .WithMany()
                        .HasForeignKey("PillarId");

                    b.HasOne("GabrielOS.Domain.Entities.User", "User")
                        .WithMany("Decisions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");

                    b.Navigation("Pillar");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.Goal", b =>
                {
                    b.HasOne("GabrielOS.Domain.Entities.Pillar", "Pillar")
                        .WithMany("Goals")
                        .HasForeignKey("PillarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GabrielOS.Domain.Entities.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pillar");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.Initiative", b =>
                {
                    b.HasOne("GabrielOS.Domain.Entities.Goal", "Goal")
                        .WithMany("Initiatives")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.JournalEntry", b =>
                {
                    b.HasOne("GabrielOS.Domain.Entities.Decision", "Decision")
                        .WithMany("JournalEntries")
                        .HasForeignKey("DecisionId");

                    b.HasOne("GabrielOS.Domain.Entities.Goal", "Goal")
                        .WithMany("JournalEntries")
                        .HasForeignKey("GoalId");

                    b.HasOne("GabrielOS.Domain.Entities.Pillar", "Pillar")
                        .WithMany("JournalEntries")
                        .HasForeignKey("PillarId");

                    b.HasOne("GabrielOS.Domain.Entities.User", "User")
                        .WithMany("JournalEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Decision");

                    b.Navigation("Goal");

                    b.Navigation("Pillar");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.Metric", b =>
                {
                    b.HasOne("GabrielOS.Domain.Entities.Pillar", "Pillar")
                        .WithMany("Metrics")
                        .HasForeignKey("PillarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GabrielOS.Domain.Entities.User", "User")
                        .WithMany("Metrics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pillar");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.MonthlyReview", b =>
                {
                    b.HasOne("GabrielOS.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.Pattern", b =>
                {
                    b.HasOne("GabrielOS.Domain.Entities.User", "User")
                        .WithMany("Patterns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.Pillar", b =>
                {
                    b.HasOne("GabrielOS.Domain.Entities.User", "User")
                        .WithMany("Pillars")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("GabrielOS.Domain.Entities.Goal", "Goal")
                        .WithMany("Tasks")
                        .HasForeignKey("GoalId");

                    b.HasOne("GabrielOS.Domain.Entities.Initiative", "Initiative")
                        .WithMany("Tasks")
                        .HasForeignKey("InitiativeId");

                    b.HasOne("GabrielOS.Domain.Entities.User", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");

                    b.Navigation("Initiative");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.WeeklyReview", b =>
                {
                    b.HasOne("GabrielOS.Domain.Entities.User", "User")
                        .WithMany("WeeklyReviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.CycleFocus", b =>
                {
                    b.Navigation("CycleFocusGoals");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.Decision", b =>
                {
                    b.Navigation("JournalEntries");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.Goal", b =>
                {
                    b.Navigation("CycleFocusGoals");

                    b.Navigation("Initiatives");

                    b.Navigation("JournalEntries");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.Initiative", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.Pillar", b =>
                {
                    b.Navigation("Goals");

                    b.Navigation("JournalEntries");

                    b.Navigation("Metrics");
                });

            modelBuilder.Entity("GabrielOS.Domain.Entities.User", b =>
                {
                    b.Navigation("CheckIns");

                    b.Navigation("CycleFocuses");

                    b.Navigation("Decisions");

                    b.Navigation("Goals");

                    b.Navigation("JournalEntries");

                    b.Navigation("Metrics");

                    b.Navigation("Patterns");

                    b.Navigation("Pillars");

                    b.Navigation("Tasks");

                    b.Navigation("WeeklyReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
